tap "homebrew/cask-fonts"

brew "fzf"
brew "gh"
brew "git"
brew "lazygit"
brew "neovim"
brew "overmind"
brew "reattach-to-user-namespace"
brew "ripgrep"
brew "zoxide"

cask "alacritty"
cask "font-meslo-lg-nerd-font"
